<a href="https://colab.research.google.com/github/SangatMaharjan/Machine-Learning-CSE/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Working with Dictionary and DataFrame

In [ ]:
#Working with Dictionary

# A data structure used to store data in key value pairs

student= {
    "name" : "John" ,
    "age" : 20 ,
    "faculty" : "BCE"
}

print(student["name"])

John

In [ ]:
# Access Value

print(student["name"])

John

In [ ]:
# Use Get() function

student.get("name")

'John'

In [ ]:
# Add item

student["address"] = "Lalitpur"

print(student)

{'name': 'John', 'age': 20, 'faculty': 'BCE', 'address': 'Lalitpur'}

In [ ]:
# Update Value

student["name"]= "Jacob"
print(student)

{'name': 'Jacob', 'age': 20, 'faculty': 'BCE', 'address': 'Lalitpur'}

In [ ]:
# Remove item using del

del student["age"]
print(student)

{'name': 'Jacob', 'faculty': 'BCE', 'address': 'Lalitpur'}

In [ ]:
# Remove using pop

student.pop("faculty")
print(student)

{'name': 'Jacob', 'address': 'Lalitpur'}

In [ ]:
# Remove Last Item

student.popitem()
print(student)

{'name': 'Jacob'}

In [ ]:
# Clear Dictionary

student.clear()
print(student)

{}

In [ ]:
# Copy Dictionary

student = {
    "name": "John",
    "age": 20,
    "faculty": "BCE"
}

# Use an underscore instead of a space
new_stud = student.copy()

print(new_stud)

{'name': 'John', 'age': 20, 'faculty': 'BCE'}

In [ ]:
# Get All Keys
new_stud.keys()

dict_keys(['name', 'age', 'faculty'])

In [ ]:
# Get All Values
new_stud.values()

dict_values(['John', 20, 'BCE'])

In [ ]:
# Get All Items

new_stud.items()

dict_items([('name', 'John'), ('age', 20), ('faculty', 'BCE')])

In [ ]:
# Check Key Exists

"name" in new_stud
"marks" in new_stud
"address" in new_stud

False

In [ ]:
# Get Length

len(new_stud)

3

In [ ]:
# Loop Through Keys

for k in new_stud:
  print(k)

name
age
faculty

In [ ]:
#Loop Through Values

for v in new_stud.values():
  print(v)

John
20
BCE

In [ ]:
# Loop Through Items

for k, v in new_stud.items():
    print(f"key: {k} and Value: {v}")

key: name and Value: John
key: age and Value: 20
key: faculty and Value: BCE

In [ ]:
# Working With Pandas DataFrame

''' A DataFrame in Python is a two-dimensional, tabular data structure that organizes
data into labeled rows and columns. It is conceptually identical to an Excel
spreadsheet or a SQL table, making it the primary tool for data manipulation and
analysis in the Pandas Library. '''

In [ ]:
# Create a DataFrame

import pandas as pd
student1= {
    "name" : "John" ,
    "age" : 20 ,
    "faculty" : "BCE" ,
    "marks":91
}

student2={
    "name" : "Jacob" ,
    "age" : 21,
    "faculty" : "BCE" ,
    "marks":68
}

student3= {
    "name" : "Rachel" ,
    "age": 23 ,
    "faculty":"BCV" ,
    "marks" : 81
}
student4={
    "name": "Roman" ,
    "age":20 ,
    "faculty":"ARCH" ,
    "marks" : 78
}
student5= {
    "name": "Rock" ,
    "age": 19 ,
    "faculty":"BEIT" ,
    "marks":89
}

student6={
    "name": "Victor" ,
    "age": 21 ,
    "faculty": "BCE" ,
    "marks": 97
}
df = pd.DataFrame([student6 , student1, student2,student3,student4 , student5])
print(df)

df1=pd.DataFrame([student1, student2, student3])

     name  age faculty  marks
0  Victor   21     BCE     97
1    John   20     BCE     91
2   Jacob   21     BCE     68
3  Rachel   23     BCV     81
4   Roman   20    ARCH     78
5    Rock   19    BEIT     89

In [ ]:
# Display the first 5 rows of the DataFrame

df.head()

     name  age faculty  marks
0  Victor   21     BCE     97
1    John   20     BCE     91
2   Jacob   21     BCE     68
3  Rachel   23     BCV     81
4   Roman   20    ARCH     78

In [ ]:
# Display the last 5 rows of the DataFrame

df.tail()

     name  age faculty  marks
1    John   20     BCE     91
2   Jacob   21     BCE     68
3  Rachel   23     BCV     81
4   Roman   20    ARCH     78
5    Rock   19    BEIT     89

In [ ]:
# Find the total number of rows and columns in the DataFrame

df.shape

(6, 4)

In [ ]:
# Display all column names in the DataFrame

df.columns

Index(['name', 'age', 'faculty', 'marks'], dtype='object')

In [ ]:
''' Display complete information about the DataFrame including dtat
data types and memory usage  '''

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   faculty  6 non-null      object
 3   marks    6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
# Generate a statistical summary of numerical columns in DataFramwe

df.describe()

             age      marks
count   6.000000   6.000000
mean   20.666667  84.000000
std     1.366260  10.430724
min    19.000000  68.000000
25%    20.000000  78.750000
50%    20.500000  85.000000
75%    21.000000  90.500000
max    23.000000  97.000000

In [ ]:
# Select and display the Name Column from DataFrame

df['name']

0    Victor
1      John
2     Jacob
3    Rachel
4     Roman
5      Rock
Name: name, dtype: object

In [ ]:
# Select and display mulitple columns such as Name and Marks

df[['name' , 'faculty']]

     name faculty
0  Victor     BCE
1    John     BCE
2   Jacob     BCE
3  Rachel     BCV
4   Roman    ARCH
5    Rock    BEIT

In [ ]:
#Display the first row of the DataFrame using positional indexing

df.iloc[0]

name       Victor
age            21
faculty       BCE
marks          97
Name: 0, dtype: object

In [ ]:
# Display the first row of DataFrame using label based indexing

df.loc[0]

name       Victor
age            21
faculty       BCE
marks          97
Name: 0, dtype: object

In [ ]:
#Access a specific cell value such as Age of the first student

df.loc[0,'age']

df.loc[1,'age']

df.loc[1,'name']

'John'

In [ ]:
 #Filter and display students whose Age is greater than 21

 df[df['age']>21]

     name  age faculty  marks
3  Rachel   23     BCV     81

In [ ]:
# Filter and display students whose age is greater than 20 and faculty is BCe

df[(df['age']>20) & (df['faculty']=='BCE')]

     name  age faculty  marks
0  Victor   21     BCE     97
2   Jacob   21     BCE     68

In [ ]:
#Add a new column called Grade to the DataFrame

df['Grade']=['A','A','C','B+','B','A-']
print(df)

     name  age faculty  marks Grade
0  Victor   21     BCE    102     A
1    John   20     BCE     96     A
2   Jacob   21     BCE     73     C
3  Rachel   23     BCV     86    B+
4   Roman   20    ARCH     83     B
5    Rock   19    BEIT     94    A-

In [ ]:
# Increase all students marks by 5

df['marks'] = df['marks']+ 5

In [ ]:
# Update the Marks of Jacob to 85 using a condition

df.loc[df['name']=='Jacob','marks']=95
print(df)

     name  age faculty  marks Grade
0  Victor   21     BCE    102     A
1    John   20     BCE     96     A
2   Jacob   21     BCE     95     C
3  Rachel   23     BCV     86    B+
4   Roman   20    ARCH     83     B
5    Rock   19    BEIT     94    A-

In [ ]:
def assign_grade(mark):
    if mark >= 90:
        return 'A+'
    elif mark >= 80:
        return 'A'
    elif mark >= 70:
        return 'B'
    else:
        return 'F'

df['grade'] = df['marks'].apply(assign_grade)
print(df)

     name  age faculty  marks Grade grade
0  Victor   21     BCE    102     A    A+
1    John   20     BCE     96     A    A+
2   Jacob   21     BCE     95     C    A+
3  Rachel   23     BCV     86    B+     A
4   Roman   20    ARCH     83     B     A
5    Rock   19    BEIT     94    A-    A+

In [ ]:
# Remove the other Grade Column

# axis =1 signifies we remove the entire vertical column
df=df.drop('Grade',axis=1)
print(df)

     name  age faculty  marks grade
0  Victor   21     BCE    102    A+
1    John   20     BCE     96    A+
2   Jacob   21     BCE     95    A+
3  Rachel   23     BCV     86     A
4   Roman   20    ARCH     83     A
5    Rock   19    BEIT     94    A+

In [ ]:
# Remove the first row from the data frame

df=df.drop(0, axis=0)
print(df)

     name  age faculty  marks grade
1    John   20     BCE     96    A+
2   Jacob   21     BCE     95    A+
3  Rachel   23     BCV     86     A
4   Roman   20    ARCH     83     A
5    Rock   19    BEIT     94    A+

In [ ]:
#Sort the DataFrame by Marks in ascending order

df.sort_values('marks')

     name  age faculty  marks grade
4   Roman   20    ARCH     83     A
3  Rachel   23     BCV     86     A
5    Rock   19    BEIT     94    A+
2   Jacob   21     BCE     95    A+
1    John   20     BCE     96    A+

In [ ]:
# Sort the DataFramy by marks in Descending Order

df.sort_values('marks', ascending=False)

     name  age faculty  marks grade
1    John   20     BCE     96    A+
2   Jacob   21     BCE     95    A+
5    Rock   19    BEIT     94    A+
3  Rachel   23     BCV     86     A
4   Roman   20    ARCH     83     A

In [ ]:
# Concatenate two DataFrames Verticallly

pd.concat([df,df1])

     name  age faculty  marks
0  Victor   21     BCE     97
1    John   20     BCE     91
2   Jacob   21     BCE     68
3  Rachel   23     BCV     81
4   Roman   20    ARCH     78
5    Rock   19    BEIT     89
0    John   20     BCE     91
1   Jacob   21     BCE     68
2  Rachel   23     BCV     81

In [124]:
# Creating the CSV file
# Write the DataFrame into a CSV File

df.to_csv('students.csv',index=False)

In [125]:
# Read data from a CSV file into a DataFrame

pd.read_csv('students.csv')

     name  age faculty  marks
0  Victor   21     BCE     97
1    John   20     BCE     91
2   Jacob   21     BCE     68
3  Rachel   23     BCV     81
4   Roman   20    ARCH     78
5    Rock   19    BEIT     89

In [128]:
# Create an excel file
# Write the DataFrame into an Excel File
df.to_excel('students_data.xlsx', index=False)

In [130]:
# Read Data From Excel File into a Dataframe

pd.read_excel('students_data.xlsx')

     name  age faculty  marks
0  Victor   21     BCE     97
1    John   20     BCE     91
2   Jacob   21     BCE     68
3  Rachel   23     BCV     81
4   Roman   20    ARCH     78
5    Rock   19    BEIT     89